### PR TITLE
Fixed arquillian tests

### PR DESCRIPTION
**Pull request by Jmacek**

### CODE REVIEW

**Comment by KSU-Github** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AttendanceAssignment.java#L56](https://github.com/kstateome/lti-attendance/blob/4672eff21bbbf4377a837538af1671130941da7d/src/main/java/edu/ksu/canvas/attendance/entity/AttendanceAssignment.java#L56): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.ome.ksu.edu/coding_rules#rule_key=squid%3AS1186)
1. MINOR [ArquillianSpringMVCConfig.java#L68](https://github.com/kstateome/lti-attendance/blob/4672eff21bbbf4377a837538af1671130941da7d/src/test/java/edu/ksu/canvas/attendance/config/arquillian/ArquillianSpringMVCConfig.java#L68): Make this final field static too. [rule](https://sonar.ome.ksu.edu/coding_rules#rule_key=squid%3AS1170)
1. MINOR [ArquillianSpringMVCConfig.java#L68](https://github.com/kstateome/lti-attendance/blob/4672eff21bbbf4377a837538af1671130941da7d/src/test/java/edu/ksu/canvas/attendance/config/arquillian/ArquillianSpringMVCConfig.java#L68): Rename this field "FAKE_DOMAIN" to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.ome.ksu.edu/coding_rules#rule_key=squid%3AS00116)

**Comment by kawesome** [comment]
Can one of the admins verify this patch?

**Comment by Jmacek** [comment]
Changing to Merge branch 34N

**Comment by Jmacek** [comment]
Changed base branch, reopening

**Pull request merged**
